name: stun_slider
description: A custom Flutter slider widget with dynamic page sizes in both dimensions, enabling smooth and adaptable user interaction.
version: 1.2.1
homepage: https://stun-apps.com/
repository: https://github.com/STUN-Apps-Dev/stun_slider
issue_tracker: https://github.com/STUN-Apps-Dev/stun_slider/issues

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
